ktor {
  deployment {
    port = 8080
    port = ${?PORT}
  }
  application {
    modules = [
      com.gblrod.orbitalnexus.plugins.KoinKt.configureKoin
      com.gblrod.orbitalnexus.plugins.SerializationKt.configureSerialization
      com.gblrod.orbitalnexus.plugins.StatusPagesKt.configureStatusPages
      com.gblrod.orbitalnexus.plugins.RoutingKt.configureRouting
      com.gblrod.orbitalnexus.plugins.SwaggerKt.configureSwagger
    ]
  }
}