CREATE TABLE planets (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(30) NOT NULL
);

CREATE TABLE planet_translations (
    planet_id INTEGER NOT NULL,
    locale VARCHAR(10) NOT NULL,
    description TEXT NOT NULL,

    PRIMARY KEY (planet_id, locale),

    FOREIGN KEY (planet_id)
        REFERENCES planets (id)
);

CREATE TABLE missions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(30) NOT NULL,
    planet_id INTEGER NOT NULL,
    launch_year INTEGER NOT NULL,
    FOREIGN KEY (planet_id) REFERENCES planets (id)
);

CREATE TABLE mission_translations (
    mission_id INTEGER NOT NULL,
    locale VARCHAR(10) NOT NULL,
    mission_objective TEXT NOT NULL,
    description TEXT NOT NULL,

    PRIMARY KEY (mission_id, locale),

    FOREIGN KEY (mission_id) REFERENCES missions (id)
);

CREATE TABLE astronauts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(30) NOT NULL,
    nationality VARCHAR(30) NOT NULL,
    image VARCHAR(500),
    mission_id INTEGER NOT NULL,
    FOREIGN KEY (mission_id) REFERENCES missions (id)
);